import type { Metadata } from "next";
import "./css/globals.css";
import Layout from "@/components/layout";
import Header from "@/components/header";
import Menu from "@/components/menu";

export const metadata: Metadata = {
  title: {
    template: "Ollomnify.io",
    default: "Ollomnify.io",
  },
  description: "Generated by Matthias Alexander",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-bodyFont w-full bg-white text-darkText">
        <Layout>
          <Header />
          <Menu />
          {children}
        </Layout>
      </body>
    </html>
  );
}
